[workspace]
resolver = "2"

members = [
    "gkr", "elliptic-curve",
    "fiat-shamir-transcript", "field",
    "polynomial",
    "shamir-secret-sharing",
    "sumcheck", "multilinear-kzg", "signature-schemes",
]
