[package]
name = "signature-schemes"
version = "0.1.0"
edition = "2021"

[dependencies]

ark-bls12-381 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.2"
rand = "0.8.5"
rayon = "1.10.0"
ark-serialize = "0.4.2"
blake2 = "0.10.6"
